context:
  type: context
  handler:
    name: env-context
backend:
  api:
    type: web
    handler:
      name: graphql-api
clients:
  web:
    type: web
    handler:
      name: express-ssr
    depends_on:
      - backend.api
